server:
  port: 8084

spring:
  application:
    name: ai-service
    datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

